# ArgoCD App: Deploy ESO Configurations (SecretStore & ExternalSecret)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nabe39/vohongduc-aws-accelerator-p2.git
    path: cloud/w10/lab/eso
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
