apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db-secret
  namespace: development
spec:
  refreshInterval: 1m # Tần suất đồng bộ (thỏa mãn yêu cầu rotate secret < 60s)
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: k8s-db-secret # Tên K8s Secret được tự động sinh ra/cập nhật trong namespace này
    creationPolicy: Owner
  data:
    - secretKey: database-password # Key trong K8s Secret
      remoteRef:
        key: dev/app/mysql # Tên Secret trên AWS Secrets Manager
        property: password # Key chứa giá trị mật khẩu trong JSON payload trên AWS
    - secretKey: database-username
      remoteRef:
        key: dev/app/mysql
        property: username
