apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db-secret
  namespace: demo
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: k8s-db-secret
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: dev/app/mysql
        property: password
    - secretKey: database-username
      remoteRef:
        key: dev/app/mysql
        property: username
